CONTROLLER_HEART_BEAT_EXPIRATION = 30
WORKER_HEART_BEAT_INTERVAL = 15

LOGDIR = "."

# Model Constants
IGNORE_INDEX = -100
IMAGE_TOKEN_INDEX = -200
DEFAULT_IMAGE_TOKEN = "<image>"
# DEFAULT_IMAGE_PATCH_TOKEN = "<im_patch>"
DEFAULT_IM_START_TOKEN = "<im_start>"
DEFAULT_IM_END_TOKEN = "<im_end>"
IMAGE_PLACEHOLDER = "<image-placeholder>"

DEFAULT_IMAGE_PATCH_TOKEN = "<patch>"
DEFAULT_PATCH_START_TOKEN = "<patch_start>"
DEFAULT_PATCH_END_TOKEN = "<patch_end>"

# DEFAULT_VIDEO_TOKEN = "<video>"
DEFAULT_VIDEO_START_TOKEN = "<video_start>"
DEFAULT_VIDEO_END_TOKEN = "<video_end>"

# DEFAULT_VIDEO_FRAME_TOKEN = "<frame>"
# DEFAULT_FRAME_START_TOKEN = "<frame_start>"
# DEFAULT_FRAME_END_TOKEN = "<frame_end>"

DEFAULT_THUMBNAIL_START_TOKEN = "<thumbnail_start>"
DEFAULT_THUMBNAIL_END_TOKEN = "<thumbnail_end>"